// lesson24/button-groups-react/src/components/ButtonsGroup.tsx
import { Dispatch, SetStateAction } from "react";

type Props = {
  set: Dispatch<SetStateAction<"" | "red" | "blue" | "green">>;
};

function ButtonsGroup({ set }: Props) {
  return (
    <>
      <button onClick={() => set("red")}>red</button>
      <button onClick={() => set("green")}>green</button>
      <button onClick={() => set("blue")}>blue</button>
    </>
  );
}

export default ButtonsGroup;

// lesson24/button-groups-svelte/src/lib/ButtonsGroup.svelte
<script lang="ts">
    import {createEventDispatcher} from 'svelte';

    const dispatch = createEventDispatcher<{
        set: "red" | "green" | "blue";
    }>();
</script>

<button on:click={() => dispatch("set", "red")}>red</button>
<button on:click={() => dispatch("set", "green")}>green</button>
<button on:click={() => dispatch("set", "blue")}>blue</button>
