// officehour2/bmi-svelte/src/App.svelte
<script lang="ts">
  const FEET_PER_METER = 3.28084;
  const LBS_PER_KG = 2.204623;

  let type = "metric";
  let height = 0;
  let weight = 0;

  function updateType(type: string) {
    if (type === "imperial") {
      height = height * FEET_PER_METER;
      weight = weight * LBS_PER_KG;
    } else {
      height = height / FEET_PER_METER;
      weight = weight / LBS_PER_KG;
    }
  }

  $: updateType(type)

  $: bmi = (() => {
    if (type === "imperial") {
      return ((weight) / (height * height)) * 703
    } else {
      return (weight) / (height * height)
    }
  })()
</script>

<main>
  <form class="form">
    <label>
      <input type="radio" name="type" value="metric" bind:group={type} />
      <span>Metric</span>
    </label>
    <label>
      <input type="radio" name="type" value="imperial" bind:group={type} />
      <span>Imperial</span>
    </label>
    <label>
      <span>Height</span>
      <input type="number" name="height" bind:value={height}/>
      {#if type === 'imperial'}
        <span>ft</span>
      {:else}
        <span>m</span>
      {/if}
    </label>
    <label>
      <span>Weight</span>
      <input type="number" name="weight" bind:value={weight}/>
      {#if type === 'imperial'}
        <span>lbs</span>
      {:else}
        <span>kg</span>
      {/if}
    </label>
    <label>
      <output>{bmi}</output>
    </label>
  </form>
</main>

<style>
  .form {
    display: flex;
    flex-direction: column;
  }
</style>

// officehour2/bmi-react/src/App.tsx
import { ChangeEvent, MouseEvent, useMemo, useState } from "react";
import "./App.css";

function App() {
  const [type, setType] = useState("");
  const [height, setHeight] = useState(0);
  const [weight, setWeight] = useState(0);

  function handleTypeClick(event: MouseEvent<HTMLInputElement>) {
    const { currentTarget } = event;

    setType(currentTarget.value);
  }

  function handleHeightChange(event: ChangeEvent<HTMLInputElement>) {
    const { currentTarget } = event;

    setHeight(currentTarget.valueAsNumber);
  }

  function handleWeightChange(event: ChangeEvent<HTMLInputElement>) {
    const { currentTarget } = event;

    setWeight(currentTarget.valueAsNumber);
  }

  const bmi = useMemo(() => {
    if (type === "imperial") {
      return (weight / (height * height)) * 703;
    } else {
      return weight / (height * height);
    }
  }, [type, weight, height]);

  return (
    <main>
      <form className="form">
        <label>
          <input
            type="radio"
            name="type"
            value="metric"
            onClick={handleTypeClick}
          />
          <span>Metric</span>
        </label>
        <label>
          <input
            type="radio"
            name="type"
            value="imperial"
            onClick={handleTypeClick}
          />
          <span>Imperial</span>
        </label>
        <label>
          <span>Height</span>
          <input
            type="number"
            name="height"
            value={height}
            onChange={handleHeightChange}
          />
          {type === "imperial" ? <span>ft</span> : <span>m</span>}
        </label>
        <label>
          <span>Weight</span>
          <input
            type="number"
            name="weight"
            value={weight}
            onChange={handleWeightChange}
          />
          {type === "imperial" ? <span>lb</span> : <span>kg</span>}
        </label>
        <label>
          <output>{bmi}</output>
        </label>
      </form>
    </main>
  );
}

export default App;
